GET http://localhost:5050/dashboard
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiR2lhY29tbyIsInN1cm5hbWUiOiJDYXNvbG8iLCJlbWFpbCI6ImdpYWNvbW9AbWUuaXQiLCJkYXRlT2ZCaXJ0aCI6IjE5OTEvMTAvMDUiLCJfaWQiOiI2NGM4ZWIyYjg0MDlkZTIxODYzYmRiZTQiLCJpYXQiOjE2OTA5MTg4NTgsImV4cCI6MTY5MTAwNTI1OH0.ptXIN2o8zG65c3Rqhm6XLsRSgxoqtOdpUYAclj1PUsw


