#####
GET http://localhost:5050/resources/

#####
GET http://localhost:5050/resources/isActive?isActive=true

#####
GET http://localhost:5050/resources/ageRange?minAge=26&maxAge=30

#####
GET http://localhost:5050/resources/eyeBrownOrBlue?eye=blue&eye=brown

#####
GET http://localhost:5050/resources/eyeDifferentColor?eye=green

#####
GET http://localhost:5050/resources/eyeColorsDifferent?eye=blue&eye=brown

#####
GET http://localhost:5050/resources/company?companyName=FITCORE